import './globals.css'
import { Poppins } from 'next/font/google'
import Header from './components/header/Header'
import { ClerkProvider } from '@clerk/nextjs'
import { shadesOfPurple } from '@clerk/themes'


const poppins = Poppins({ subsets: ['latin'] , weight: ['100', '700' , '800'] , })

export const metadata = {
  title: 'Clerk Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <ClerkProvider appearance={{
        baseTheme:shadesOfPurple
      }}>
      <Header/>
      {children}
      </ClerkProvider>
      </body>
    </html>
  )
}
